### ISSUE TITLE
Wrong method calls to existing endpoints raise 404, not 405

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-web-api#138]
See here:

_Originally posted by @DavidMStraub in https://github.com/gramps-project/web-api/issues/135#issuecomment-748670881_

**Comment by jeffasuk** [comment]
This doesn't seem to be a universal problem.
I tried several methods with /api/types/
PUT and DELETE got a 405, which I believe is correct.
POST got a 404, which is the bug in this issue.
