### ISSUE TITLE
Database schema upgrade workflow

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-web-api#428]
As part of #424, I realized we don't have any workflow for upgrading the schema of the database from the API, i.e. without access to the server. This will be necessary for users upgrading their servers to Gramps 5.2.

@Nick-Hall what do you think -  we could simply set `force_schema_upgrade=True` in the Web API's database loader, so the first request occurring after the upgrade would trigger the database upgrade, and then serve the response as if nothing happened (only with a delay). The question is what to do when something goes wrong. The UI does a ZIP backup of the database, but that doesn't work for Postgres, and anyway is not helpful when a user doesn't have direct server access. I guess in practice, we have to tell users to create backups (which I hope they're anyway doing regularly) _before_ performing the upgrade.

**Comment by Nick-Hall** [comment]
Your other option is to import the backup from the previous version into a new empty tree.

**Comment by Nick-Hall** [comment]
The database plugins were developed for 5.0 which is schema version 19.  Therefore, all backends using DbGeneric will be schema version 19.   It looks like the VERSION variable has been set incorrectly, but this hasn't really mattered until now.

Gramps version 5.2 requires a schema upgrade to version 20.  We need to check that a database with an incorrect version number doesn't run a 18 to 19 upgrade on a database the is already actually version 19.

As this next release is the first time a non-BSDDB backend will need an upgrade, we should test this thoroughly.  I haven't done so yet.  Thanks for pointing this out.
