### ISSUE TITLE
Disable registration

### ISSUE THREAD

**Issue by andrewvaughan** [gramps-project/gramps-web-api#475]
Apologies if this is already a feature and I'm just somehow  missing it - my family hopes to have a private (but publicly available) Gramps installation. This would mean disabling the Registration form in the login page. Is this possible? If not, please consider it as a feature, as I imagine this is a significant use-case.

**Comment by hdholm** [comment]
@lucaberti That was a concern for me as well, although I don't want to disable registration entirely  - I do want to allow family to "refer" others.  Which just now makes me think some sort of referral system might be interesting, but that's not what I came to say.  I have Gramps Web running from an nginx reverse proxy with nginx listening on a high, non-standard port.  nginx is set up to only proxy requests from the proper vhost name, so even if you just hit the port with IP scan you get a 404.  So for no random registration requests.  It doesn't look like scanners are even finding IP to be honest.  Scanning all the high ports is a lot of work for scammers looking for low-hanging fruit.  Although the site has only been up a few weeks.  Just something for you to consider.

**Comment by lucaberti** [comment]
@DavidMStraub ...and it is a pity that Gramps is not popular as Wordpress ;) Thank you for having takan seriously my request: i tend to consider all software whos security policy is this-will-neve-happen-to-us-because-no-one-is-interested-in-hacking-us as bed design an, thus, not trustworty. Thank you for not beeing that type of programmer. That said, I'm afraid I cannot be te contributor you are looking for. Not yet, at least.
@hdholm  Thank you for sharing your experienced. It's reasuring and gives me some ideas on how to implement. Currently I'm using nginx reverse proxy to reroute to my internal docker the domain call.

**Comment by DavidMStraub** [comment]
> I do want to allow family to "refer" others.

Actually, there is a simple way to achieve that which might also be sufficient for your @lucaberti: in the multi-tree setup, which is meant for hosting multiple Gramps databases in parallel (but you can limit yourself to a single one...), an additional tree ID is required for registration. This tree ID is a UUIDv4, so it is impossible to guess. In Gramps Web, the administrator will see the registration link in the settings (it has the form `https://somehost/register/<uuid>`. See https://www.grampsweb.org/user-guide/registration/. (Although a warning, it might be not all subtleties of the multi-tree setup are well documented yet, given that it's a relatively new feature meant for advanced users.)

**Comment by lucaberti** [comment]
> > I do want to allow family to "refer" others.
> 
> Actually, there is a simple way to achieve that which might also be sufficient for your @lucaberti: in the multi-tree setup, which is meant for hosting multiple Gramps databases in parallel (but you can limit yourself to a single one...), an additional tree ID is required for registration. This tree ID is a UUIDv4, so it is impossible to guess. In Gramps Web, the administrator will see the registration link in the settings (it has the form `https://somehost/register/<uuid>`. See https://www.grampsweb.org/user-guide/registration/. (Although a warning, it might be not all subtleties of the multi-tree setup are well documented yet, given that it's a relatively new feature meant for advanced users.)

Indeed this seems a good solution. I will try it when I have some spare time. Thank you!

**Comment by zackcover** [comment]
> > as this is a portal to a LOT of PII
> 
> Can you please elaborate? Would like to understand better.

This post has actually been really helpful to me. It’s easy to understand and effective.

What you need to do is, in your Gramps directory, create an empty file named `config.js`. This file should only contain the JavaScript code that the user included in their post.

In your Docker Compose file, under the Gramps service, you should add something like this in the Volumes section:
volumes:
      (whatever you already have)
      - ./config.js:/app/static/config.js:ro

This way, you "override" the code that renders the login screen, disabling the "Create Account" button.

**Comment by lokesh-krishna** [comment]
Can anyone share what the contents of the `config.js` file need to be? The original link doesn't exist anymore.

**Comment by DavidMStraub** [comment]
https://www.grampsweb.org/install_setup/frontend-config/
