### ISSUE TITLE
"Number of persons" in a tree is not updated after deleting all the records in a tree

### ISSUE THREAD

**Issue by hartenthaler** [gramps-project/gramps-web-api#502]
After deleting all the records in a tree, the management console still shows the old number of persons in the GUI.

![Screenshot (32)](https://github.com/gramps-project/gramps-web-api/assets/6324175/e5497e42-dc9a-4700-ad3a-5ea6c672028f)

**Comment by DavidMStraub** [comment]
Oh, good catch, thanks

**Comment by DavidMStraub** [comment]
By the way, as a temporary workaround, adding a single person should reset it to the correct value.

**Comment by hartenthaler** [comment]
Yes, that workaround is ok.
