### ISSUE TITLE
Cannot establish Grampsweb Synchronisation with dokker-compose

### ISSUE THREAD

**Issue by Dan-cer** [gramps-project/gramps-web-api#516]
I followed the instructions on [this page](https://www.grampsweb.org/Deployment/). I wanted to start the "First-run wizard" with the command "docker-compose up -d".
After several attempts - also with the "Secure access with SSL/TLS" version - and download ("pull") of a total of approx. 5 GB and following some advice on the net, e.g. removing the container, I am now at a point where I can't get any further without your help.
If I now start the command "docker-compose up -d" in the /var/www/html directory, I get
`docker-compose up -d
grampsweb_redis is up-to-date
e0885c687992_html_grampsweb_1 is up-to-date
grampsweb_celery is up-to-date`

However, the wizard still does not appear. With "docker-compose up" the output shows some problems. For example these lines:

`/usr/local/lib/python3.11/dist-packages/gramps/plugins/tool/check.py:51: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
html_grampsweb_1 | from gi.repository import Gtk`

I have noticed that the directory `/usr/local/lib/python3.11/dist-packages/` is empty. I can't find the `gramps` folder or `celery` and its subfolders there. 
There is instead a directory `/usr/lib/python3/dist-packages/gramps/plugins/tool/check.py`.
I can't figure out how to load the correct gtk version.

How can I repair it?
I add the output of `docker-compose up` in terminal as txt file.
[docker-compose up.txt](https://github.com/gramps-project/gramps-web-api/files/15236489/docker-compose.up.txt)

**Comment by DavidMStraub** [comment]
Hi @Dan-cer, it doesn't look like this is an issue of Gramps Web API. Posting in the Gramps forum as you have done [here](https://gramps.discourse.group/t/recurring-problems-with-gramps-web/5506/2) was the right thing to do.
