### ISSUE TITLE
Fan chart doesn't work

### ISSUE THREAD

**Issue by hcscherzer609** [gramps-project/gramps-web-api#537]
I tried the demo family on gramshub and did not succeed to get the fan chart work

**Comment by DavidMStraub** [comment]
Hi,

since it works for me, it must be a browser or frontend issue.

![grafik](https://github.com/user-attachments/assets/b1d86de2-5a98-4202-9b3f-9b5ba72531da)

Are you using Safari? Then it's a duplicate of https://github.com/gramps-project/gramps-web/issues/452.

**Comment by hcscherzer609** [comment]
Yes, it's a Safari problem.
Chrome and Firefox: OK

**Comment by DavidMStraub** [comment]
Thanks for confirming.
