### ISSUE TITLE
New setuptools-scm based install does not work with current Dockerfile

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-web-api#548]
@JohnRDOrazio, after merging #547, the docker image doesn't build anymore, because we just copy the source files and install from there, so it fails with 

```
LookupError: setuptools-scm was unable to detect version for /app/src.
```

**Comment by DavidMStraub** [comment]
I suppose the easiest fix would be to

**Comment by DavidMStraub** [comment]
All of my attempts to fix this failed. @JohnRDOrazio let's reinstate an explicit version in pyproject.toml instead of using setuptools-scm.

**Comment by JohnRDOrazio** [comment]
I'm not very familiar with build tools in python, so go ahead and do what you think is best
