### ISSUE TITLE
Gramps ID format

### ISSUE THREAD

**Issue by chtiland** [gramps-project/gramps-web-api#551]
Hello !

On my desktop Gramps I set id formats with **%08d**. But when I deployed Gramps Web and import gramps datas, ID is a **%04d** format.

Quite annoying because on the other hand I also use Dokuwiki for my genealogy, and links are "built" with %08d format as I use in desktop application.

When I add a new object in Gramps Web, then ID is **%08d** format. Something wrong with 

Gramps Desktop 5.2.2 (from Ubuntu 24.04 LTS repos)

Gramps Web : 

- Gramps 5.2.2
- Gramps Web API 2.3.1
- Gramps Web Frontend 24.7.0
- Gramps QL 0.3.0

**Comment by emyoulation** [comment]
Neither Gramps for desktops nor Gramps Web for servers respect the leading zeros format contained in the XML data imported. It seems wrong to do a transform by default.  That should be an explicit override.

**Comment by DavidMStraub** [comment]
True but I don't even think we need to track that here specifically, because this is all handled by Gramps core.
