### ISSUE TITLE
Profiling

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-web-api#70]
I started doing some profiling on the endpoints to see if there are any performance bottlenecks that can be easily fixed. I also started rebuilding my web app to see whether our current API implementation works as a backend (I think this can be helpful to find issues we haven't thought of).

For a single `people/handle`, I measured an execution time of 67 ms on my machine, but with lots of time wasted by debug logging (I opened [an issue](https://github.com/gramps-project/gramps/pull/1147) in the Gramps repo).

For the entire `people` endpoint using the example DB, it took 0.7 s, which is not that bad, given there are more than 2000 people in the DB.

However, I noticed that with the `profile` option enabled, it takes almost 10 seconds (and my laptop is certainly faster than most web servers). That's a problem because for any app building a simple of people names and birthdays, this is just too long. Profiling with `snakeviz` showed that most of the time is needed to recurse through family members, and switching of `with_family` brings it back down to 1.5 seconds, which is kind of OK. So I think we have to provide a way to switch this off. I will open a separate issue. Note that even `extend=all` only increases the time to 2.2 seconds, which I find quite impressive.

Here is the notebook I'm using for profiling: https://gist.github.com/DavidMStraub/ea72c7a966d5ecf1ff4b14b418ec0feb

We can use this thread for any further observations.

**Comment by cdhorn** [comment]
I think it is great you are doing this now!  I also agree, once you're app starts making use of it I am sure that will help uncover things overlooked, needing change, etc.

**Comment by DavidMStraub** [comment]
The bottleneck for increasing startup time of the Gramps.js frontend at the moment is the `metadata` endpoint. Profiling it, I found that surprisingly 57% of the time is spent executing `inspect.stack` in Gramps debug statements, and 40% is spent parsing `apispec.yaml` to get the version number.

**Comment by DavidMStraub** [comment]
Unfortunately, it seems the 57% (which is more than 1 second) can only be solved by the Gramps PR I already opened more than 1 year ago:
https://github.com/gramps-project/gramps/pull/1147
At the moment, this time consuming call to `inspect.stack` is even done when debug logging is disabled and the Python `-O` flag is used, which is completely useless.

**Comment by DavidMStraub** [comment]
I was able to reduce the calling time for `/metadata` from 1000 ms (after applying #244) to 50 ms by adding

```python
from unittest.mock import patch
with patch('inspect.stack'):
```
in several places (in webapi, not gramps). This is a horrible hack, no doubt, but I find it hard to accept that we pay a factor of 20 in response time just because of some debug statements nobody sees. Any better ideas?
